# ==================================================================================
# 博客系统核心文章管理模块 - 测试环境配置
# ==================================================================================
# 环境：Test
# 说明：测试环境专用配置，用于集成测试、UAT测试等
# 特点：中等日志级别、测试数据库、端口隔离、部分调试功能
# ==================================================================================

# --- 服务器配置 ---
server:
  port: 8081

# --- Spring 框架配置 ---
spring:
  datasource:
    url: jdbc:mysql://test-db:3306/blog_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:blog_test_user}
    password: ${DB_PASSWORD:test_password}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: BlogArticleHikariCP-TEST

  # --- JPA 配置 ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# --- MyBatis-Plus 测试配置 ---
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# --- 日志配置 ---
logging:
  level:
    root: INFO
    com.zm.blog: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/blog-article-service-test.log

# --- Swagger 配置 ---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# --- Actuator 配置 ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# --- 跨域配置 ---
cors:
  allowed-origins: http://test-frontend:3000,http://test.example.com

# --- JWT 测试配置 ---
jwt:
  secret: ${JWT_SECRET:test_jwt_secret_key_for_testing_environment_only}
  expiration: 7200

# --- 功能配置 ---
feature:
  article:
    max-title-length: 150
    max-content-length: 30000
    auto-save-interval: 60

# --- 基础设施配置 ---
infra:
  cache:
    enabled: true
    ttl: 1800
  file:
    upload-path: ${FILE_UPLOAD_PATH:/var/test/uploads}
    max-size: 5MB