# ===================================================================
# 博客系统核心文章管理模块 - 测试环境配置
# ===================================================================

# --- Spring Boot 测试环境配置 ---
spring:
  config:
    activate:
      on-profile: test

  # --- 数据库配置（测试环境使用H2内存数据库） ---
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  # --- H2 控制台配置（测试环境启用） ---
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # --- JPA 测试环境配置 ---
  jpa:
    hibernate:
      ddl-auto: create-drop  # 测试环境自动创建和删除表
    show-sql: false  # 测试环境不显示SQL语句
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  # --- 测试环境日志配置 ---
logging:
  level:
    root: WARN
    com.zm.blog: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  # --- 文件上传配置 ---
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # --- 缓存配置 ---
  cache:
    type: simple
    cache-names: articles, users, categories

  # --- 测试环境性能配置 ---
  main:
    lazy-initialization: true  # 延迟初始化以加快启动速度

# --- 服务器配置 ---
server:
  port: 8081
  servlet:
    context-path: /

# --- 测试环境跨域配置（限制允许的源） ---
cors:
  allowed-origins: http://test-frontend:3000,http://test-frontend:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# --- 测试环境Swagger配置（启用API文档） ---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false

# --- 测试环境JWT配置（使用测试密钥） ---
app:
  jwt:
    secret: test-jwt-secret-key-change-in-production
    expiration: 3600  # 1小时，单位秒
    refresh-expiration: 86400  # 1天，单位秒

# --- 测试环境管理端点配置（暴露部分端点） ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# --- 测试环境调试配置 ---
debug: false