# =================================================================
# Production Environment Configuration
# =================================================================
# 使用场景：生产环境，安全配置，优化性能，禁用调试功能

# --- Server Configuration ---
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 2048

# --- Logging Configuration ---
logging:
  level:
    root: WARN
    com.zm.blog: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
  file:
    name: ${LOG_FILE:/var/log/blog/blog-prod.log}
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 90
      total-size-cap: 1GB

# --- Database Configuration (Production) ---
spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

  # --- Security Configuration ---
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:}
    headers:
      frame-options: DENY
      xss-protection: 1; mode=block
      content-type-options: nosniff
      strict-transport-security: max-age=31536000; includeSubDomains

  # --- Development Tools ---
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: true

  # --- CORS Configuration (Production) ---
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,Accept
    allow-credentials: false
    max-age: 3600

  # --- Performance Configuration ---
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: false
    time-zone: UTC

# --- Application Configuration ---
app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: ${JWT_EXPIRATION:3600}

# --- Swagger/OpenAPI ---
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    shutdown:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

# --- Production-specific Configuration ---
prod:
  monitoring:
    enabled: true
    metrics-export: prometheus
  cache:
    enabled: true
    ttl: 3600
  backup:
    enabled: true
    schedule: "0 2 * * *"