# ===================================================================
#                Development Environment Configuration
# ===================================================================
# Development profile configuration for local development
# Activated by: --spring.profiles.active=dev

# --- Development Server Configuration ---
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true

# --- Development Database Configuration ---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # --- Development JPA Configuration ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # --- Development H2 Console (for testing) ---
  h2:
    console:
      enabled: false

  # --- Development File Upload Configuration ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

  # --- Development Redis Configuration (Optional) ---
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3000

  # --- Development Validation Configuration ---
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

  # --- Development Internationalization (i18n) ---
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  # --- Development Features Configuration ---
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  thymeleaf:
    cache: false

# --- Development MyBatis-Plus Configuration ---
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# --- Development Logging Configuration ---
logging:
  level:
    root: INFO
    com.zm.blog: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/blog-article-service-dev.log
    max-size: 10MB
    max-history: 30

# --- Development Application Configuration ---
app:
  version: 0.1.0
  name: Blog Article Service (Development)
  description: Blog Article Management System - Development Environment
  debug: true

  # --- Development CORS Configuration ---
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# --- Development JWT Configuration ---
jwt:
  secret: dev-secret-key-for-jwt-token-generation
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds
  header: Authorization
  prefix: Bearer

# --- Development Swagger/OpenAPI Configuration ---
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# --- Development Management/Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

