# ===================================================================
#                Test Environment Configuration
# ===================================================================
# Test profile configuration for testing environment
# Activated by: --spring.profiles.active=test

# --- Test Server Configuration ---
server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true

# --- Test Database Configuration ---
spring:
  datasource:
    url: jdbc:mysql://test-db-host:3306/blog_test?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # --- Test JPA Configuration ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  # --- Test File Upload Configuration ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 0

  # --- Test Redis Configuration ---
  data:
    redis:
      host: ${REDIS_HOST:test-redis}
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 1
      timeout: 3000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 1
          max-wait: 3000

  # --- Test Validation Configuration ---
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

  # --- Test Internationalization (i18n) ---
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  # --- Test Security Configuration ---
  security:
    user:
      name: ${TEST_ADMIN_USER:admin}
      password: ${TEST_ADMIN_PASSWORD:admin123}

# --- Test MyBatis-Plus Configuration ---
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# --- Test Logging Configuration ---
logging:
  level:
    root: INFO
    com.zm.blog: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/blog-article-service-test.log
    max-size: 50MB
    max-history: 30

# --- Test Application Configuration ---
app:
  version: 0.1.0
  name: Blog Article Service (Test)
  description: Blog Article Management System - Test Environment
  debug: false

  # --- Test CORS Configuration ---
  cors:
    allowed-origins: http://test-frontend:3000,http://test-frontend:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# --- Test JWT Configuration ---
jwt:
  secret: ${JWT_SECRET:test-jwt-secret-key}
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds
  header: Authorization
  prefix: Bearer

# --- Test Swagger/OpenAPI Configuration ---
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: false
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# --- Test Management/Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      simple:
        enabled: true

