spring:
    application:
        name: blog-article-service
    profiles:
        active: dev
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    messages:
        basename: messages
        encoding: UTF-8
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# --- Application Metadata ---
app:
    version: 0.1.0
    name: Blog Article Service
    description: Blog article management service

# --- Server Configuration ---
server:
    port: 8080
    servlet:
        context-path: /

# --- Logging Configuration ---
logging:
    level:
        root: INFO
        com.zm.blog: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# --- MyBatis-Plus Configuration ---
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            id-type: auto
            logic-delete-field: deleted
            logic-delete-value: 1
            logic-not-delete-value: 0

# --- JWT Configuration (Placeholder) ---
jwt:
    secret: ${JWT_SECRET:your-secret-key-here}
    expiration: ${JWT_EXPIRATION:86400}

# --- Actuator Configuration ---
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: when-authorized