# =================================================================
# Test Environment Configuration
# =================================================================
# 使用场景：测试环境，模拟生产配置但启用详细日志用于调试

# --- Server Configuration ---
server:
  port: 8082

# --- Logging Configuration ---
logging:
  level:
    root: INFO
    com.zm.blog: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
  file:
    name: logs/blog-test.log

# --- Database Configuration (Test) ---
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://test-db:3306/blog_test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # --- Development Tools ---
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: true

  # --- CORS Configuration (Test) ---
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://test-frontend:3000,http://test-api:8082}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,Accept
    allow-credentials: true
    max-age: 3600

# --- Application Configuration ---
app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: 3600

# --- Swagger/OpenAPI ---
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
    shutdown:
      enabled: false

# --- Test-specific Configuration ---
test:
  data:
    auto-cleanup: true
    sample-data-size: 100