# =================================================================
# Development Environment Configuration
# =================================================================
# 使用场景：本地开发环境，启用调试模式，详细日志输出

# --- Server Configuration ---
server:
  port: 8081

# --- Logging Configuration ---
logging:
  level:
    root: DEBUG
    com.zm.blog: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/blog-dev.log

# --- Database Configuration (Development) ---
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/blog_dev?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # --- Development Tools ---
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  # --- CORS Configuration (Development) ---
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080,http://localhost:8081
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# --- Application Configuration ---
app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-123456}
    expiration: 604800

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

# --- Debug Configuration ---
debug: true
trace: true